import Head from 'next/head';
import { Navbar } from '../components'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Head>
        <title>Contactame</title>
      </Head>
      <Navbar />
      <h1>INDEX</h1>
    </>
  )
}
